name: React Frontend CI/CD

on:
  push:
    paths:
      - 'book-fn/**'
  pull_request:
    paths:
      - 'book-fn/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: book-fn
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          VITE_API_URL: https://book-hub-5.onrender.com
        run: npm test -- --watchAll=false

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: book-fn
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build --build-arg VITE_API_URL=https://book-hub-5.onrender.com -t react-frontend .
      # Here add your deploy step
      # Example for Render:
      - name: Deploy to Render
        uses: render-examples/render-github-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: your-frontend-service-id
          branch: main
