name: React Frontend CI/CD

on:
  push:
    paths:
      - 'book-fn/**'
  pull_request:
    paths:
      - 'book-fn/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: book-fn
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          VITE_API_URL: https://book-hub-5.onrender.com
        run: npm test -- --watchAll=false

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: book-fn
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build --build-arg VITE_API_URL=https://book-hub-5.onrender.com -t react-frontend .
      # Add deploy step here for your provider (e.g., Render, Netlify, etc)
